#-------------------------------
# General Site Settings
title: min-33320
logo: logo.svg # You can add own logo.
description: Hello, I'm min! :)


#-------------------------------
# Author Settings
author:
  name: Bomin Namkoong
  image: 01.jpg
  say-hello: Hello, I’m <strong>Bomin Namkoong</strong>
  bio: I'm studying <strong>electrical and electronic enginerring</strong> and <strong>computer science</strong>. Loves <a href="#">music</a> & baking.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/gloria_nk_/ # Add your Instagram handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: min # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: gloria_nk_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
